version: '2'
services:
  proxy:
    image: navikt/syfoproxy:latest
    ports:
      - "8080:80"
    volumes:
      - ".:/var/run/secrets/nais.io/vault"
    depends_on:
      - syfotekster
  syfotekster:
    build: .
