apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfotekster-v2
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: repo.adeo.no:5443/syfo/syfotekster-v2:{{VERSION}}
  port: 80
  team: teamsykefravr
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /isReady
    initialDelay: 10
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  ingresses:
    - "https://syfotekster-v2.nais.preprod.local"
    - "https://syfotekster-v2.nais.adeo.local"
